---
driver:
  name: digitalocean
  region: sfo1
  size: 2gb
  ipv6: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    attributes:
      openssh:
        server:
          permit_root_login: without-password

suites:
  - name: default
    run_list:
      - recipe[dnsimple_demo]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        demo_id: <%= ENV['DNSIMPLE_DEMO_ID'] %>
